### ISSUE TITLE
Typo at L72 in Chrome.ahk? 

### ISSUE THREAD

**Issue by cansakirt** [G33kDude/Chrome.ahk#1]
Line 72 in Chrome.ahk

 `RegRead, ChromePath, HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\**App Pahs**\chrome.exe`

https://github.com/G33kDude/Chrome.ahk/blob/master/Chrome.ahk#L72

**Comment by G33kDude** [comment]
Good catch, [I missed the letter `t` when typing it](https://autohotkey.com/boards/viewtopic.php?p=217376#p217376). Thanks for the reminder!
