### ISSUE TITLE
PageInst := ChromeInst.GetPage() does not work - Script Error

### ISSUE THREAD

**Issue by tdalon** [G33kDude/Chrome.ahk#10]
The script stops on this line:
PageInst := ChromeInst.GetPage()
I get also such a Script Error window: 
![image](https://user-images.githubusercontent.com/6458444/62211245-4a0bc200-b39e-11e9-894a-799c6bc73d2c.png)

Any idea?
I use Chrome 76

**Comment by fdaf11** [comment]
https://stackoverflow.com/questions/15114279/websocket-on-ie10-giving-a-securityerror/20145203#20145203

**Comment by G33kDude** [comment]
This should no longer be a problem in V1.3.0
