### ISSUE TITLE
Wrong path chrome.lnk in Chrome.ahk_v1.2(Release)

### ISSUE THREAD

**Issue by mschadev** [G33kDude/Chrome.ahk#13]
###  script.ahk line 77

Wrong path
``HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Pahs\chrome.exe``

correct path
``HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\chrome.exe``

**Comment by G33kDude** [comment]
Duplicate of #1

**Comment by Nirvanatin** [comment]
There have been tons of wasted hours as a result of this typo.
