### ISSUE TITLE
New Chrome User Profile issue.

### ISSUE THREAD

**Issue by goglgo** [G33kDude/Chrome.ahk#22]
The error occurs when make new chrome user profile.

I think, some patch makes "--user-data-dir=" argument get only abstract folder path.

so, write correct path or attach previous script path. may be the solve.

Chrome.ahk Line 91
Like this.
`Run, % this.CliEscape(ChromePath)
. " --remote-debugging-port=" this.DebugPort
. (ProfilePath ? " --user-data-dir=" . this.CliEscape(**A_ScriptDir . "\" .** ProfilePath) : "")
. (Flags ? " " Flags : "")
. URLString
,,, OutputVarPID`

if do that, it can solve some other issues I think.

**Comment by G33kDude** [comment]
This should be fixed by 1.3.0
