### ISSUE TITLE
Problem getting started

### ISSUE THREAD

**Issue by kevin28115** [G33kDude/Chrome.ahk#24]
I seem to have the same issue as 
https://github.com/G33kDude/Chrome.ahk/issues/19

I'm running a single line of code to try to learn how it works
PageInst.Call("Page.navigate", {"url": "https://autohotkey.com/"})

and the error I get is
![image](https://user-images.githubusercontent.com/37888579/120739285-43c95e00-c4bf-11eb-8138-2e65c9a81897.png)

**Comment by martin-lim** [comment]
download the zip file from the release page, rather than the source code.
