### ISSUE TITLE
Cannot read properties  of undefined (reading 'click') at <anonymous>:1:83

### ISSUE THREAD

**Issue by Elanuroquesalta** [G33kDude/Chrome.ahk#27]
So, after cleaning some other errors, im still getting trouble with the code line where the JavaScript begins. Im still new to this language, so i cant find the source of the problem yet.

Any ideas?

![image](https://user-images.githubusercontent.com/92059738/136446009-91a921e9-6763-40b2-bd12-3417df17df89.png)

**Comment by SaifAqqad** [comment]
There's a problem with your selector `'#post-4101 > div > p:nth-child(4) > a:nth-child(4)'`, because the first element of the returned `NodeList` is undefined.
Open the page in a browser and make sure it works there
