### ISSUE TITLE
include file errors

### ISSUE THREAD

**Issue by Fohsap** [G33kDude/Chrome.ahk#35]
Downloading the zip file, it does not include the libs; so, I downloaded the libs manually. 
It is necessary to include some lines like #Include %A_MyDocuments%/autohotkey/chrome.ahk for some users, but that's a separate matter.
If this is done properly, and chrome.ahk is included, I am assuming that json.ahk and jxon.ahk come from your other repo because clicking on the folder in the code links to your autohotkeyjson repo; so, I downloaded those and put them in the %A_MyDocuments%/autohotkey/lib directory. 
Resulting error: call to nonexistent function in include file jxon.ahk specifically: jxon_dump(k) line 165-184 (see image).
![image](https://user-images.githubusercontent.com/3434880/222064203-605bb79b-4295-479b-a5c5-d9eab0ee0ab4.png)

**Comment by G33kDude** [comment]
You downloaded the development files, they do not come with the libraries. Download the release files.

https://github.com/G33kDude/Chrome.ahk/releases/tag/1.2
