### ISSUE TITLE
WebSocket Error

### ISSUE THREAD

**Issue by TechBarat** [G33kDude/Chrome.ahk#36]
Hello,

I have been using the latest Chrome.ahk for some personal purposes for a long time now, suddenly when I wanted to run a script yesterday, once it tried to execute the GetPage() function, I got a Script error with "Websocket Error!"
I did not change anything in my script, it opens a webpage in Chrome started in debug mode (port 9222 is used), and I have the same issue in my other scripts just with different URLs opened.
Could someone please help me, or advise how to solve this problem?

![image](https://user-images.githubusercontent.com/127327772/223763257-2e96f46e-d18d-465d-8a24-ff0bbb0442e0.png)

Thank you,
Gabor

**Comment by cn0360** [comment]
I get same problom here. Even the example file in original libary doesn't work anymore.

**Comment by cn0360** [comment]
@malcev and @neogna2 share the solution in [Here](https://www.autohotkey.com/boards/viewtopic.php?f=6&t=42890&sid=0465226ce040b65f57d4e1c61b9c96ab&start=620) .

**Comment by G33kDude** [comment]
Fixed by db1f68862664a1736f0c538406ee853020b3f37b
