### ISSUE TITLE
How to restore the backspace key as a keyboard shortcut to go back in Chrome

### ISSUE THREAD

**Issue by ghost** [G33kDude/Chrome.ahk#4]
Shift+Backspace

**Comment by G33kDude** [comment]
This library, and AutoHotkey in general, is not very well suited for this task.

Your best option would be to download the extension that Google offers to restore this functionality that you can download here: https://chrome.google.com/webstore/detail/go-back-with-backspace/eekailopagacbcdloonjhbiecobagjci
