### ISSUE TITLE
posting error..

### ISSUE THREAD

**Issue by adegard** [G33kDude/Chrome.ahk#6]

**Comment by jdpmdphd** [comment]
Why does this come up empty on a chrome page with --debug to 9222
!c::
   WinGetTitle,title,A
   Page:=Chrome.GetPageByTitle(title, "exact")
   list:=Page.GetPageList()
   dump1:=Chrome.Jxon_Dump(list)
   findContinue:="document.evaluate('//button',document,null,XPathResult.ANY_TYPE,null).iterateNext()"
   result:=Page.Execute(findContinue)
   dump2:=Chrome.Jxon_Dump(result)
   tooltip % "title='" title "'`ndump:'" dump1 "`n:" dump2 "' `nFrom " Page.GetAddress
return
-jdpmdphd@gmail.com
